# Generated by Django 6.0.4 on 2026-04-13 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_notes_patient_phone_allergy_medication_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('heart_rate', models.PositiveIntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.visit')),
            ],
            options={
                'ordering': ['-visit__visit_date', '-collected_at', '-id'],
            },
        ),
    ]
