# Generated by Django 6.0.4 on 2026-04-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_vital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='primary_language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
