# Generated by Django 6.0.4 on 2026-04-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_primary_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('current', 'Current'), ('chronic', 'Chronic'), ('remission', 'Remission'), ('resolved', 'Resolved')], default='current', max_length=20)),
                ('date_diagnosed', models.DateField()),
                ('diagnosis_code', models.CharField(blank=True, max_length=30)),
                ('provider_name', models.CharField(blank=True, max_length=150)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient')),
            ],
            options={
                'ordering': ['-date_diagnosed', 'name'],
            },
        ),
    ]
