# Generated by Django 6.0.4 on 2026-04-21 19:13

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def migrate_legacy_visit_notes(apps, schema_editor):
    Visit = apps.get_model("patients", "Visit")
    VisitNote = apps.get_model("patients", "VisitNote")
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)

    legacy_author, _ = User.objects.get_or_create(
        username="legacy_visit_note",
        defaults={
            "first_name": "Legacy",
            "last_name": "Visit Note",
            "email": "",
            "password": make_password(None),
            "is_active": False,
        },
    )

    for visit in Visit.objects.exclude(notes=""):
        VisitNote.objects.get_or_create(
            visit=visit,
            author=legacy_author,
            defaults={"content": visit.notes},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_diagnosis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_notes', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='patients.visit')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('visit', 'author'), name='unique_visit_note_per_author')],
            },
        ),
        migrations.RunPython(migrate_legacy_visit_notes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='visit',
            name='notes',
        ),
    ]
