# Generated by Django 6.0.4 on 2026-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_visit_notes_visitnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
