# Generated by Django 6.0.4 on 2026-04-22 06:32

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def migrate_legacy_diagnosis_notes(apps, schema_editor):
    Diagnosis = apps.get_model("patients", "Diagnosis")
    DiagnosisNote = apps.get_model("patients", "DiagnosisNote")
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)

    legacy_author, _ = User.objects.get_or_create(
        username="legacy_diagnosis_note",
        defaults={
            "first_name": "Legacy",
            "last_name": "Diagnosis Note",
            "email": "",
            "password": make_password(None),
            "is_active": False,
        },
    )

    for diagnosis in Diagnosis.objects.exclude(notes=""):
        DiagnosisNote.objects.get_or_create(
            diagnosis=diagnosis,
            author=legacy_author,
            defaults={"content": diagnosis.notes},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_medication_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_notes', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='patients.diagnosis')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('diagnosis', 'author'), name='unique_diagnosis_note_per_author')],
            },
        ),
        migrations.RunPython(migrate_legacy_diagnosis_notes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='diagnosis',
            name='notes',
        ),
    ]
