# Generated by Django 6.0.4 on 2026-04-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_diagnosis_notes_diagnosisnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-is_active', 'name']},
        ),
        migrations.AddField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
