# Generated by Django 6.0.4 on 2026-04-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='patient_card_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
