"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    if not path.exists():
        return

    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'\"")
        os.environ.setdefault(key, value)


def get_env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def get_env_str(name, default=""):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip()


def get_env_email_password(name, default=""):
    value = os.environ.get(name)
    if value is None:
        return default

    password = value.strip()
    return "".join(password.split())


def get_env_path(name, default=""):
    value = get_env_str(name, default)
    if not value:
        return ""
    return str((BASE_DIR.parent / value).resolve()) if not value.startswith("/") else value


def get_env_int(name, default):
    value = os.environ.get(name)
    if value is None:
        return default

    try:
        return int(value)
    except (TypeError, ValueError):
        return default


load_env_file(BASE_DIR / ".env")
load_env_file(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-development-key",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts',
    'patients',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'medical_chart'),
        'USER': os.environ.get('DB_USER', 'medical_chart_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'medical_chart_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {},
    }
}

DB_SSLMODE = get_env_str("DB_SSLMODE", "disable")
DB_SSLROOTCERT = get_env_path("DB_SSLROOTCERT", "")
DB_SSLCERT = get_env_path("DB_SSLCERT", "")
DB_SSLKEY = get_env_path("DB_SSLKEY", "")

if DB_SSLMODE and DB_SSLMODE != "disable":
    DATABASES["default"]["OPTIONS"]["sslmode"] = DB_SSLMODE
    if DB_SSLROOTCERT:
        DATABASES["default"]["OPTIONS"]["sslrootcert"] = DB_SSLROOTCERT
    if DB_SSLCERT:
        DATABASES["default"]["OPTIONS"]["sslcert"] = DB_SSLCERT
    if DB_SSLKEY:
        DATABASES["default"]["OPTIONS"]["sslkey"] = DB_SSLKEY


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


CORS_ALLOW_ALL_ORIGINS = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

DEFAULT_FROM_EMAIL = get_env_str("DEFAULT_FROM_EMAIL", "no-reply@medical-chart.local")
EMAIL_BACKEND = get_env_str(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = get_env_str("EMAIL_HOST", "localhost")
EMAIL_PORT = get_env_int("EMAIL_PORT", 25)
EMAIL_USE_TLS = get_env_bool("EMAIL_USE_TLS", False)
EMAIL_HOST_USER = get_env_str("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = get_env_email_password("EMAIL_HOST_PASSWORD", "")
DATA_ENCRYPTION_KEY = get_env_str("DATA_ENCRYPTION_KEY", "")

MFA_CODE_TTL_MINUTES = get_env_int("MFA_CODE_TTL_MINUTES", 10)
MFA_RESEND_THROTTLE_SECONDS = get_env_int("MFA_RESEND_THROTTLE_SECONDS", 30)
MFA_MAX_FAILED_ATTEMPTS = get_env_int("MFA_MAX_FAILED_ATTEMPTS", 5)
