version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: medical
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  backend:
    build: ./infra/docker/backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./infra/docker/frontend
    ports:
      - "5173:5173"
